include:
  - project: 'rnd/gitlab-ci-templates'
    ref: main
    file:
      - "docker-build-template.yml"

image: docker:latest

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^dev-|^qa-|^stg-|^prod-/'
      when: always
    - when: never
stages:
  - build
  - deploy

dockerize-and-push:
  stage: build
  extends:
    - .aws-multiplatform-ecr
  variables:
    AWS_ECR_IMAGE: linkifysoft/drawdb
    IMAGE_TAG: $CI_COMMIT_TAG
    MULTI_PLATFORM: 'true'
